# Play default config
play.application.loader = "loader.AppLoader"

play.http.router = "router.Routes"

# Disable auto-loading modules; we will wire dependencies manually later
play.modules.enabled = []
