# Play default config
play.application.loader = "loader.AppLoader"

play.http.router = "router.Routes"

# Disable auto-loading modules; we will wire dependencies manually later
play.modules.enabled = []

db.default.driver = "org.sqlite.JDBC"
db.default.url = "jdbc:sqlite:conf/blog.db"

scalikejdbc.global.loggingSQLAndTime.enabled = true
scalikejdbc.global.loggingSQLAndTime.logLevel = "info"
scalikejdbc.global.loggingSQLAndTime.warningThresholdMillis = 1000
