addSbtPlugin("com.github.sbt" % "sbt-digest" % "2.1.0")
addSbtPlugin("com.github.sbt" % "sbt-gzip" % "2.0.0")
addSbtPlugin("com.github.karelcemus" % "sbt-filter" % "1.1.0")
addSbtPlugin("de.lolhens" % "sbt-css-compress" % "0.2.0")
addSbtPlugin("org.playframework" % "sbt-plugin" % "3.0.10")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.6")
