services:
  blog-play:
    build:
      context: target/docker/stage
      dockerfile: Dockerfile
    ports:
      - "${PORT:-9000}:9000"
    environment:
      PLAY_HTTP_SECRET_KEY: "${PLAY_HTTP_SECRET_KEY}"
      PLAY_ALLOWED_HOST_0: "${HOST:-.}"
      BLOG_DB_URL: "${BLOG_DB_URL:-jdbc:h2:mem:blog;MODE=PostgreSQL;DB_CLOSE_DELAY=-1}"
    volumes:
      - ./data:/opt/docker/data
