FROM sbtscala/scala-sbt:graalvm-community-25.0.1_1.12.6_3.8.2 AS build
COPY ./ /app/
WORKDIR /app

FROM build AS agent

FROM build AS native-build
RUN sbt play/GraalVMNativeImage/packageBin

FROM almalinux:latest AS app
WORKDIR /app
COPY --from=native-build /app/play/target/graalvm-native-image/* .
ENTRYPOINT ["./blog-play"]
