zio.http.port = 9000
zio.http.port = ${?ZIO_HTTP_PORT}

db.default.driverClassName = "org.h2.Driver"
db.default.driverClassName = ${?BLOG_DB_DRIVER}
db.default.jdbcUrl = "jdbc:h2:file:./zio/data/blog;MODE=PostgreSQL"
db.default.jdbcUrl = ${?BLOG_DB_URL}
db.default.username = ""
db.default.username = ${?BLOG_DB_USER}
db.default.password = ""
db.default.password = ${?BLOG_DB_PASSWORD}

blog.datetime.format = "yyyy/MM/dd HH:mm"
