zio.http.port = 9001
zio.http.port = ${?ZIO_HTTP_PORT}

db.default.driver = "org.h2.Driver"
db.default.driver = ${?BLOG_DB_DRIVER}
db.default.url = "jdbc:h2:file:./play/data/blog;MODE=PostgreSQL"
db.default.url = ${?BLOG_DB_URL}
db.default.user = "sa"
db.default.user = ${?BLOG_DB_USER}
db.default.password = ""
db.default.password = ${?BLOG_DB_PASSWORD}

blog.datetime.format = "yyyy/MM/dd HH:mm"
